### ISSUE TITLE
Add some preview pictures to the README?

### ISSUE THREAD

**Issue by vladvisan** [mahendrapaipuri/ceems#93]
I feel it would help advertise the project.
The corresponding tool for OAR does it: https://github.com/oar-team/colmet?tab=readme-ov-file#introduction

**Comment by mahendrapaipuri** [comment]
@vladvisan Cheers for the interest and feedback.

Yes, I agree. I have not really started working on docs part yet. There are couple of critical features in the pipeline now and once they are onboarded, I will work on docs part and add more screenshots.

**Comment by vladvisan** [comment]
It looks good!

**Comment by mahendrapaipuri** [comment]
@vladvisan Appreciate the feedback. 

I see that you work with UGA. If you are interested in using it for your center, feel free to contact me. Would be happy to collaborate.

**Comment by vladvisan** [comment]
@mahendrapaipuri Thank you, I've asked around and replied by e-mail.
